name: Build and Publish

on:
    label:
      types:
        - created
    workflow_dispatch:

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            submodules: 'true'
        
        - name: Apply patches
          run: |
                cd DnsServer && git apply ../fix-single-file-publish.patch

        - name: Setup .NET
          uses: actions/setup-dotnet@v4.2.0
          with:
            dotnet-version: '8.0.x'

        - name: Build TechnitiumLibrary
          run: |
                dotnet build TechnitiumLibrary/TechnitiumLibrary.ByteTree/TechnitiumLibrary.ByteTree.csproj -c Release
                dotnet build TechnitiumLibrary/TechnitiumLibrary.Net/TechnitiumLibrary.Net.csproj -c Release

        - name: Build DnsServer
          run: |
                dotnet publish -r linux-x64 -p:PublishSingleFile=true --self-contained DnsServer/DnsServerApp/DnsServerApp.csproj -c Release

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            path: DnsServer/DnsServerApp/bin/Release/linux-x64/publish/