name: Build and Publish

on:
    label:
      types:
        - created
    workflow_dispatch:

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: 'true'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.2.0
        with:
            dotnet-version: '8.0.x'

      - name: Build TechnitiumLibrary
        run: |
            dotnet build TechnitiumLibrary/TechnitiumLibrary.ByteTree/TechnitiumLibrary.ByteTree.csproj -c Release
            dotnet build TechnitiumLibrary/TechnitiumLibrary.Net/TechnitiumLibrary.Net.csproj -c Release

      - name: Build DnsServer
        run: |
            dotnet publish DnsServer/DnsServerApp/DnsServerApp.csproj -c Release
            

    #   - name: Build
    #     run: dotnet build ./src/Project.csproj --configuration Release --no-restore

    #   - name: Publish
    #     run: dotnet publish ./src/Project.csproj --configuration Release --output ./bin/Release/net6.0/publish

    #   - name: Upload binaries
    #     uses: actions/upload-artifact@v2
    #     with:
    #       name: dotnet-binaries
    #       path: ./bin/Release/net6.0/publish